Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -33,8 +33,15 @@ jobs:
           git checkout -b tmp
 
           # Push to master branch and capture the output
-          push_output=$(git push $PWS_URL tmp:master 2>&1)
-          if [[ $? -ne 0 ]]; then
+          push_output=$(git push $PWS_URL tmp:master 2> push_error.log)
+          exit_code=$?
+
+          if [[ -s push_error.log ]]; then
+            echo "Standard Error: "
+            cat push_error.log
+          fi
+
+          if [[ $exit_code -ne 0 ]]; then
             echo "Push failed with output: $push_output"
             echo "Error: Unable to push changes. Please check the error message above and resolve any conflicts manually."
             exit 1
